version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/cicd
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: ec2-user
