FROM ruby:3.3.2

ENV LANG=C.UTF-8 \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

# Install any required Linux packages (example: nodejs & yarn)
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app


# Install bundler
RUN gem install bundler

CMD ["irb"]
