production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  port: <%= ENV["DB_PORT"] %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
